# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9f02da5fda6bb67995942467b07229e0303b66d77156f194ec9e52e69cd9a04011310ea8bf563a2e09efedc5a631c9d785096ecfc8ffb3655252443fd90a96a

test:
  secret_key_base: 3f1c57847e684894a62f37cbf7420bf21032bb73b79c700b4e46561296e264b3d26f09a6f132fe5cce26a867a16f7021533ac96c36290626ef32070f94e3c546

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
